Repository particle-iot/particle-cli, pull requests merged in 2019-05, with the labels that each got.

#477 Show NCP firmware modules in the output of `serial inspect`
  src/cmd/serial.js
Labels: enhancement

#485 Mesh command fixes
  npm-shrinkwrap.json
  package.json
  src/cmd/mesh.js
Labels: bug

#488 usb: particle usb reset for devices in DFU mode
  npm-shrinkwrap.json
  package.json
  src/cmd/usb.js
Labels: feature
